CFLAGS := $(shell sdl2-config --cflags)
CLIBS := $(shell sdl2-config --libs)

step-1:
	cc -o snake step-1.c $(CFLAGS) $(CLIBS)
	./snake
step-2:
	cc -o snake step-2.c $(CFLAGS) $(CLIBS)
	./snake
step-3:
	cc -o snake step-3.c $(CFLAGS) $(CLIBS)
	./snake
step-4:
	cc -o snake step-4.c $(CFLAGS) $(CLIBS)
	./snake
