CFLAGS := $(shell sdl2-config --cflags)
CLIBS := $(shell sdl2-config --libs)
OUT := ../build/snake

step-1:
	cc -o $(OUT) step-1.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-2:
	cc -o $(OUT) step-2.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-3:
	cc -o $(OUT) step-3.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-4:
	cc -o $(OUT) step-4.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-5:
	cc -o $(OUT) step-5.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-6:
	cc -o $(OUT) step-6.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-7:
	cc -o $(OUT) step-7.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-8:
	cc -o $(OUT) step-8.c $(CFLAGS) $(CLIBS)
	$(OUT)
step-9:
	cc -o $(OUT) step-9.c $(CFLAGS) $(CLIBS)
	$(OUT)